import{a as B,S as M,i as c}from"./assets/vendor-C2ySes1p.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const E="https://pixabay.com/api/",$="54018968-920e73cf119f2d437152d8f97";async function m(r,t=1){return(await B.get(E,{params:{key:$,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const l=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".load-more"),R=new M(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){if(!l)return;const t=r.map(({webformatURL:n,largeImageURL:s,tags:e,likes:o,views:a,comments:v,downloads:P})=>`
    <li class="gallery-item">
      <a href="${s}">
        <img class="gallery-image" src="${n}" alt="${e}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o}</p>
        <p><b>Views:</b> ${a}</p>
        <p><b>Comments:</b> ${v}</p>
        <p><b>Downloads:</b> ${P}</p>
      </div>
    </li>
  `).join("");l.insertAdjacentHTML("beforeend",t),R.refresh()}function O(){l&&(l.innerHTML="")}function y(){p.classList.remove("is-hidden")}function b(){p.classList.add("is-hidden")}function x(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}const S=document.querySelector(".form"),A=document.querySelector(".load-more");let i=1,q="",d=0;S.addEventListener("submit",D);async function D(r){r.preventDefault();const t=r.target.elements["search-text"].value.trim();if(!t){c.warning({message:"Please enter a search query",position:"topRight"});return}q=t,i=1,O(),L(),y();try{const n=await m(t,i);if(d=n.totalHits,n.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(n.hits);const s=Math.ceil(d/15);i<s&&x()}catch{c.error({message:"Something went wrong",position:"topRight"})}finally{b()}}A.addEventListener("click",async()=>{i++,y();try{const r=await m(q,i);g(r.hits);const t=Math.ceil(d/15);i>=t&&(L(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),H()}catch{c.error({message:"Error loading more images",position:"topRight"})}finally{b()}});function H(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}const u=document.querySelector("label");u.classList.add("form-label");const _=document.querySelector("input");_.classList.add("form-input");const w=document.querySelector("button");w.classList.add("form-btn");const f=document.createElement("div");f.classList.add("form-container");S.insertBefore(f,u);f.append(u,w);
//# sourceMappingURL=index.js.map
