import{a as P,S as E,i}from"./assets/vendor-C2ySes1p.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const R="https://pixabay.com/api/",$="54018968-920e73cf119f2d437152d8f97";async function p(o,t=1){return(await P.get(R,{params:{key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const l=document.querySelector(".gallery"),h=document.querySelector(".loader");document.querySelector(".load-more");const B=new E(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){if(!l)return;const t=o.map(({webformatURL:s,largeImageURL:c,tags:e,likes:r,views:n,comments:w,downloads:v})=>`
    <li class="gallery-item">
      <a href="${c}">
        <img class="gallery-image" src="${s}" alt="${e}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${n}</p>
        <p><b>Comments:</b> ${w}</p>
        <p><b>Downloads:</b> ${v}</p>
      </div>
    </li>
  `).join("");l.insertAdjacentHTML("beforeend",t),B.refresh()}function O(){l&&(l.innerHTML="")}function y(){h.classList.remove("is-hidden")}function b(){h.classList.add("is-hidden")}const L=document.querySelector(".form"),d=document.querySelector(".load-more");let a=1,S="",u=0;L.addEventListener("submit",x);async function x(o){o.preventDefault();const t=o.target.elements["search-text"].value.trim();if(!t){i.warning({message:"Please enter a search query",position:"topRight"});return}S=t,a=1,O(),d.classList.add("hidden"),y();try{const s=await p(t,a);if(u=s.totalHits,s.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(s.hits),s.hits.length<u&&d.classList.remove("hidden")}catch{i.error({message:"Something went wrong",position:"topRight"})}finally{b()}}d.addEventListener("click",async()=>{a++,y();try{const o=await p(S,a);g(o.hits);const t=Math.ceil(u/15);a>=t&&(d.classList.add("hidden"),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),M()}catch{i.error({message:"Error loading more images",position:"topRight"})}finally{b()}});function M(){const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}const m=document.querySelector("label");m.classList.add("form-label");const A=document.querySelector("input");A.classList.add("form-input");const q=document.querySelector("button");q.classList.add("form-btn");const f=document.createElement("div");f.classList.add("form-container");L.insertBefore(f,m);f.append(m,q);
//# sourceMappingURL=index.js.map
