import{a as M,S as R,i}from"./assets/vendor-C2ySes1p.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const $="https://pixabay.com/api/",O="54018968-920e73cf119f2d437152d8f97",h=15;async function b(o,t=1){return(await M.get($,{params:{key:O,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:h}})).data}const l=document.querySelector(".gallery"),d=document.querySelector(".loader"),u=document.querySelector(".load-more"),x=new R(".gallery a",{captionsData:"alt",captionDelay:250});function L(o){if(!l)return;const t=o.map(({webformatURL:n,largeImageURL:s,tags:e,likes:r,views:c,comments:E,downloads:B})=>`
    <li class="gallery-item">
      <a href="${s}">
        <img class="gallery-image" src="${n}" alt="${e}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${c}</p>
        <p><b>Comments:</b> ${E}</p>
        <p><b>Downloads:</b> ${B}</p>
      </div>
    </li>
  `).join("");l.insertAdjacentHTML("beforeend",t),x.refresh()}function A(){l&&(l.innerHTML="")}function S(){d&&d.classList.remove("is-hidden")}function q(){d&&d.classList.add("is-hidden")}function m(){u&&u.classList.remove("hidden")}function f(){u&&u.classList.add("hidden")}const w=document.querySelector(".form"),_=document.querySelector(".load-more");let a=1,v="",p=0;w.addEventListener("submit",D);async function D(o){o.preventDefault();const t=o.target.elements["search-text"].value.trim();if(!t){i.warning({message:"Please enter a search query",position:"topRight"});return}v=t,a=1,A(),f(),S();try{const n=await b(t,a);if(p=n.totalHits,n.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(n.hits);const s=Math.ceil(p/h);a<s?m():(f(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({message:"Something went wrong",position:"topRight"})}finally{q()}}_.addEventListener("click",async()=>{a++,S(),f();try{const o=await b(v,a);L(o.hits);const t=Math.ceil(p/h);a>=t?(f(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):m(),H()}catch{i.error({message:"Error loading more images",position:"topRight"}),m()}finally{q()}});function H(){const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}const g=document.querySelector("label");g.classList.add("form-label");const C=document.querySelector("input");C.classList.add("form-input");const P=document.querySelector("button");P.classList.add("form-btn");const y=document.createElement("div");y.classList.add("form-container");w.insertBefore(y,g);y.append(g,P);
//# sourceMappingURL=index.js.map
